[IMPL] HelloWindow Title with frame rate
terrafx/terrafx pull request #166
Opened 2020-12-17 03:11 UTC by IngmarBitter

Any sample derived from `HelloWindow` should display the frame rate in the title. This info is already available in the `OnIdle` method. It just needs to be shown. The `Title` property should only be written to if the frame rate actually changed.

2020-12-17 03:47 UTC, FiniteReality requested changes
This should absolutely *not* be using a regex. Store the FPS in a field and update the title if it has changed. Something like this:
```cs
float lastFps;
string windowTitle;
// ...
if (eventArgs.FramesPerSecond != lastFps)
{
    lastFps = eventArgs.FramesPerSecond;
    Window.Title = $"{windowTitle} ({lastFps} fps))";
}
```

2020-12-19 17:15 UTC, tannergooding commented on samples/TerraFX/Graphics/HelloWindow.cs
> +                    if (Window.Title != newTitle)
`Window.SetTitle` should already handle such a comparison

2020-12-19 23:18 UTC, IngmarBitter commented on samples/TerraFX/Graphics/HelloWindow.cs
> +                    if (Window.Title != newTitle)
fixed

2020-12-23 17:25 UTC, tannergooding approved these changes

2020-12-23 17:25 UTC, merged